# NUMPY 
#### NUMERICAL PYTHON

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[ 0.63162166,  1.24987233,  0.63968744],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [3]:
data.shape

(2, 3)

In [4]:
data.ndim

2

In [5]:
data.dtype

dtype('float64')

In [6]:
data*10

array([[  6.31621656,  12.49872332,   6.39687436],
       [-10.01965597, -10.81174799,  12.64172125]])

In [7]:
data + data

array([[ 1.26324331,  2.49974466,  1.27937487],
       [-2.00393119, -2.1623496 ,  2.52834425]])

In [8]:
data

array([[ 0.63162166,  1.24987233,  0.63968744],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [9]:
data1 = [[3,4,6],[5,7,8]]

In [10]:
type(data1)

list

In [11]:
data1 = np.array(data1)

In [12]:
data1

array([[3, 4, 6],
       [5, 7, 8]])

In [13]:
type(data1)

numpy.ndarray

In [14]:
data2 = [[5,6,7],[1,2,3]]
data2 = np.array(data2)

In [15]:
add_data = data1 + data2

In [16]:
add_data

array([[ 8, 10, 13],
       [ 6,  9, 11]])

In [17]:
add_data.shape

(2, 3)

In [18]:
add_data.ndim

2

In [19]:
add_data.dtype

dtype('int32')

In [20]:
zero = np.zeros(10)

In [21]:
z1 = np.zeros((2,3))
z1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
add = data1 + z1

In [23]:
add.dtype

dtype('float64')

In [24]:
z2 = np.zeros((2,3),dtype=int)
z2

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
emp = np.empty((3,2))

In [26]:
emp

array([[ 0.63162166,  1.24987233],
       [ 0.63968744, -1.0019656 ],
       [-1.0811748 ,  1.26417213]])

In [27]:
emp1 = np.ones((2,2,3))
print(emp1.ndim)
print(emp1.shape)
emp1

3
(2, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
# 3 Dimension array
dim3  = [[[2,3,4],[1,2,7]],[[2,3,4],[1,4,9]]]
dim3 = np.array(dim3)
dim3.shape

(2, 2, 3)

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.arange(23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [31]:
data

array([[ 0.63162166,  1.24987233,  0.63968744],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [32]:
# takes another array and produces a zeros array of the same shape and dtype
np.zeros_like(data)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
np.full((2,3),3)

array([[3, 3, 3],
       [3, 3, 3]])

In [36]:
np.full_like(data,3)

array([[3., 3., 3.],
       [3., 3., 3.]])

In [37]:
data.dtype

dtype('float64')

In [38]:
data.astype('int64')

array([[ 0,  1,  0],
       [-1, -1,  1]], dtype=int64)

# Arthematic Operation

In [39]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [40]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [41]:
arr.astype('int32')

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [44]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [45]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [46]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [48]:
# check individual in an array and return boolean 
arr3 = arr2 > arr
arr3

array([[False,  True, False],
       [ True, False,  True]])

In [49]:
arr3.dtype

dtype('bool')

In [50]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
arr1[5:8] = 12
arr1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11])

In [52]:
arr1_slicing = arr1[5:8]
arr1_slicing

array([12, 12, 12])

In [53]:
arr1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11])

In [54]:
arr1_slicing[1] = 12345

In [55]:
arr1

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9,    10,    11])

In [56]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arr[5:8] = 12

In [58]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11])

In [59]:
arr_slicing = arr[5:8]

In [60]:
arr_slicing[1] = 12345

In [61]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9,    10,    11])

In [62]:
arr_slicing[:] = 64

In [63]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9, 10, 11])

In [64]:
arr_slicing = arr[1:4]

In [65]:
arr_slicing[:] = 3 

In [66]:
arr

array([ 0,  3,  3,  3,  4, 64, 64, 64,  8,  9, 10, 11])

In [67]:
data

array([[ 0.63162166,  1.24987233,  0.63968744],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [68]:
data[0][1]

1.2498723316371572

In [69]:
emp1

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [70]:
dt = np.random.randn(2,3,3)
dt

array([[[-0.89351716, -0.92927254,  0.51550486],
        [-1.56885861, -1.00715872, -1.50128972],
        [ 0.69803009, -0.05694337,  0.98487706]],

       [[-0.47273247,  1.06826676, -0.09144018],
        [ 1.67120444, -0.13748375,  0.638973  ],
        [-0.1020429 ,  0.40501573,  0.03614495]]])

In [71]:
dt[0][0][1] #first row second list third excess list 

-0.9292725424159071

In [72]:
data 

array([[ 0.63162166,  1.24987233,  0.63968744],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [73]:
data1 = data.copy()

In [74]:
data1

array([[ 0.63162166,  1.24987233,  0.63968744],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [75]:
data1[0] = 32

In [76]:
data1

array([[32.        , 32.        , 32.        ],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [77]:
data

array([[ 0.63162166,  1.24987233,  0.63968744],
       [-1.0019656 , -1.0811748 ,  1.26417213]])

In [78]:
arr

array([ 0,  3,  3,  3,  4, 64, 64, 64,  8,  9, 10, 11])

In [79]:
arr[1:6]

array([ 3,  3,  3,  4, 64])

In [80]:
a = [[1,2,3],[4,5,6],[7,8,9]]
arr2d = np.array(a)

In [81]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr2d[:2,:1]

array([[1],
       [4]])

In [84]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [85]:
names = ['Bob','Joe','Will','Bob','Will','Joe','Joe']
names = np.array(names)

In [86]:
data = np.random.randn(7,4)

In [87]:
data

array([[-1.50202238,  0.76618261, -0.64529707,  0.55471507],
       [-0.66621052, -0.39036309, -0.51786501, -1.49877166],
       [ 1.35379922, -0.50085411,  0.2596444 ,  0.18353862],
       [ 0.06394733, -0.01867493,  0.8727906 ,  0.0944131 ],
       [-0.6387834 , -0.37630261,  0.12480683, -0.07915716],
       [ 0.89738236, -0.02031671, -0.15667881,  0.9843779 ],
       [-0.3382256 ,  0.52936764, -0.44853599,  0.94511764]])

In [88]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [89]:
data[names=='Bob']

array([[-1.50202238,  0.76618261, -0.64529707,  0.55471507],
       [ 0.06394733, -0.01867493,  0.8727906 ,  0.0944131 ]])

In [90]:
data

array([[-1.50202238,  0.76618261, -0.64529707,  0.55471507],
       [-0.66621052, -0.39036309, -0.51786501, -1.49877166],
       [ 1.35379922, -0.50085411,  0.2596444 ,  0.18353862],
       [ 0.06394733, -0.01867493,  0.8727906 ,  0.0944131 ],
       [-0.6387834 , -0.37630261,  0.12480683, -0.07915716],
       [ 0.89738236, -0.02031671, -0.15667881,  0.9843779 ],
       [-0.3382256 ,  0.52936764, -0.44853599,  0.94511764]])

In [91]:
data[names=='Bob',2:]

array([[-0.64529707,  0.55471507],
       [ 0.8727906 ,  0.0944131 ]])

In [92]:
data[names=='Bob',3]

array([0.55471507, 0.0944131 ])

In [93]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [94]:
data[~(names=='Bob')]

array([[-0.66621052, -0.39036309, -0.51786501, -1.49877166],
       [ 1.35379922, -0.50085411,  0.2596444 ,  0.18353862],
       [-0.6387834 , -0.37630261,  0.12480683, -0.07915716],
       [ 0.89738236, -0.02031671, -0.15667881,  0.9843779 ],
       [-0.3382256 ,  0.52936764, -0.44853599,  0.94511764]])

In [95]:
mask = (names == 'Bob') | (names == 'Will')

In [96]:
mask

array([ True, False,  True,  True,  True, False, False])

In [97]:
data[mask]

array([[-1.50202238,  0.76618261, -0.64529707,  0.55471507],
       [ 1.35379922, -0.50085411,  0.2596444 ,  0.18353862],
       [ 0.06394733, -0.01867493,  0.8727906 ,  0.0944131 ],
       [-0.6387834 , -0.37630261,  0.12480683, -0.07915716]])

In [98]:
data[data<0] = 0
data

array([[0.        , 0.76618261, 0.        , 0.55471507],
       [0.        , 0.        , 0.        , 0.        ],
       [1.35379922, 0.        , 0.2596444 , 0.18353862],
       [0.06394733, 0.        , 0.8727906 , 0.0944131 ],
       [0.        , 0.        , 0.12480683, 0.        ],
       [0.89738236, 0.        , 0.        , 0.9843779 ],
       [0.        , 0.52936764, 0.        , 0.94511764]])

In [99]:
a1 = np.arange(12).reshape(3,4)

In [100]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
# Fancy Indexing
a1[[-1]]

array([[ 8,  9, 10, 11]])

In [102]:
a1[[-1,1]]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [103]:
rd = np.random.randn(5,3)
rd

array([[-2.20508502, -2.17811298,  0.42455065],
       [ 1.49321458,  0.37130862, -0.98099249],
       [ 0.49629578,  0.70306932,  0.08022822],
       [ 0.50105391,  1.619853  ,  0.93406005],
       [-0.31388617, -0.22922524,  0.27905461]])

In [104]:
rd[[1,3,4],[0,1,2]]

array([1.49321458, 1.619853  , 0.27905461])

In [105]:
rd[[1, 4, 3, 2]][:, [0, 2, 1, 2]]

array([[ 1.49321458, -0.98099249,  0.37130862, -0.98099249],
       [-0.31388617,  0.27905461, -0.22922524,  0.27905461],
       [ 0.50105391,  0.93406005,  1.619853  ,  0.93406005],
       [ 0.49629578,  0.08022822,  0.70306932,  0.08022822]])

In [106]:
r = np.arange(12).reshape(3,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
r.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [108]:
r.shape

(3, 4)

In [109]:
r.swapaxes(1,1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
dt.swapaxes(1,2)

array([[[-0.89351716, -1.56885861,  0.69803009],
        [-0.92927254, -1.00715872, -0.05694337],
        [ 0.51550486, -1.50128972,  0.98487706]],

       [[-0.47273247,  1.67120444, -0.1020429 ],
        [ 1.06826676, -0.13748375,  0.40501573],
        [-0.09144018,  0.638973  ,  0.03614495]]])

In [111]:
arr = np.arange(16).reshape((2,2,4))

In [112]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [113]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [114]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [115]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [117]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [118]:
x = np.random.randn(9)
y = np.random.randn(9)
print(x,y)

[-0.44678512 -0.57773287 -0.52085014  1.08200928  0.1412268   0.43852261
  0.32231415  1.50873212  0.66985195] [ 2.62226846 -0.92106264  0.00731399 -0.95959614 -0.45949632  0.60905828
 -0.3614199   1.20533069  0.78033811]


In [119]:
np.maximum(x,y)

array([ 2.62226846, -0.57773287,  0.00731399,  1.08200928,  0.1412268 ,
        0.60905828,  0.32231415,  1.50873212,  0.78033811])

In [120]:
np.max(x)

1.5087321239476248

In [121]:
np.min(y)

-0.9595961363932394

In [122]:
remainder,wholeno = np.modf(x)

In [123]:
remainder

array([-0.44678512, -0.57773287, -0.52085014,  0.08200928,  0.1412268 ,
        0.43852261,  0.32231415,  0.50873212,  0.66985195])

In [124]:
wholeno

array([-0., -0., -0.,  1.,  0.,  0.,  0.,  1.,  0.])

In [125]:
arr = np.arange(-5,5,0.01)
arr

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [126]:
xs,ys = np.meshgrid(arr,arr)

In [127]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [128]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

## Where
#### (condition,what to do where the condition is true,where condition is false)


In [129]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
np.where(arr>4,64,arr)

array([[ 0,  1,  2,  3],
       [ 4, 64, 64, 64],
       [64, 64, 64, 64]])

In [131]:
np.mean(arr)

5.5

In [132]:
np.sum(arr)

66

In [133]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [134]:
arr.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [135]:
arr.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [136]:
arr.cumprod(axis=1)

array([[   0,    0,    0,    0],
       [   4,   20,  120,  840],
       [   8,   72,  720, 7920]], dtype=int32)

In [137]:
arr = np.random.randn(100)

In [138]:
(arr>0).sum()

48

In [139]:
bol = np.array([False,True,False,True])

In [140]:
# tests whether one or more values in an array is True, while all checks if everyvalue is True
bol.any()

True

In [141]:
bol.all()

False

In [142]:
arr = np.random.randn(6)
arr

array([ 0.60567029,  0.15116489,  0.96370386,  0.7060961 ,  1.20366916,
       -0.73678045])

In [143]:
np.sort(arr)

array([-0.73678045,  0.15116489,  0.60567029,  0.7060961 ,  0.96370386,
        1.20366916])

In [144]:
arr = np.random.randn(2,3)
arr

array([[0.91377129, 0.08185516, 1.08396201],
       [1.73278252, 0.34016395, 0.51063941]])

In [145]:
# sort using axis
s = arr.sort(axis = 1)
s

In [146]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# Unique

In [147]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [148]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

# Linear Algebra

In [149]:
 x = np.array([[1., 2., 3.], [4., 5., 6.]]) # 2 x 3

In [150]:
y = np.array([[6., 23.], [-1, 7], [8, 9]]) # 3 x 2

In [151]:
x.dot(y) # 2 x 2

array([[ 28.,  64.],
       [ 67., 181.]])

In [152]:
arr

array([[0.08185516, 0.91377129, 1.08396201],
       [0.34016395, 0.51063941, 1.73278252]])

In [153]:
# One dimention array
arr.flatten()

array([0.08185516, 0.91377129, 1.08396201, 0.34016395, 0.51063941,
       1.73278252])

In [155]:
arr.ravel()

array([0.08185516, 0.91377129, 1.08396201, 0.34016395, 0.51063941,
       1.73278252])

In [158]:
arr1 = np.ones((2,3),dtype = int)
arr1

array([[1, 1, 1],
       [1, 1, 1]])

In [160]:
arr2 = np.ones((2,3),dtype = int) * 9
arr2

array([[9, 9, 9],
       [9, 9, 9]])

In [161]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [162]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [166]:
a = [1,2,3,4,5,6,7,8,9]

In [167]:
# Split
np.split(a,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [168]:
x = [1,4,5,6,7,9,1,4]
np.split(x,[2,5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [172]:
x = [[1,4,5,6,7,9,1,4],[11,14,15,16,17,19,11,14]]
x = np.array(x)
np.split(x,[4,6],axis = 1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]),
 array([[ 7,  9],
        [17, 19]]),
 array([[ 1,  4],
        [11, 14]])]

In [173]:
arr

array([[0.08185516, 0.91377129, 1.08396201],
       [0.34016395, 0.51063941, 1.73278252]])

In [174]:
np.hstack(arr)

array([0.08185516, 0.91377129, 1.08396201, 0.34016395, 0.51063941,
       1.73278252])

In [176]:
np.vstack(arr)

array([[0.08185516, 0.91377129, 1.08396201],
       [0.34016395, 0.51063941, 1.73278252]])

In [178]:
np.vstack((arr1,arr2))

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [179]:
np.linspace(2,50)

array([ 2.        ,  2.97959184,  3.95918367,  4.93877551,  5.91836735,
        6.89795918,  7.87755102,  8.85714286,  9.83673469, 10.81632653,
       11.79591837, 12.7755102 , 13.75510204, 14.73469388, 15.71428571,
       16.69387755, 17.67346939, 18.65306122, 19.63265306, 20.6122449 ,
       21.59183673, 22.57142857, 23.55102041, 24.53061224, 25.51020408,
       26.48979592, 27.46938776, 28.44897959, 29.42857143, 30.40816327,
       31.3877551 , 32.36734694, 33.34693878, 34.32653061, 35.30612245,
       36.28571429, 37.26530612, 38.24489796, 39.2244898 , 40.20408163,
       41.18367347, 42.16326531, 43.14285714, 44.12244898, 45.10204082,
       46.08163265, 47.06122449, 48.04081633, 49.02040816, 50.        ])